# Generated by Django 3.1.7 on 2021-03-06 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wine", "0002_auto_20210304_2235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="points",
        ),
        migrations.AddField(
            model_name="library",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wine",
            name="library",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wines",
                to="wine.library",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100)
                        ]
                    ),
                ),
                ("comment", models.CharField(max_length=1000, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="wine.wine",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
