# Generated by Django 3.1.7 on 2021-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0004_auto_20210306_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="library",
            field=models.ManyToManyField(
                related_name="libraries", to="wine.Library"
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="wine.Tag"),
        ),
    ]
