# Generated by Django 3.1.7 on 2021-03-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0005_auto_20210306_1118"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine",
            old_name="library",
            new_name="libraries",
        ),
    ]
