# Generated by Django 3.1.7 on 2021-03-08 18:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0006_auto_20210306_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=30,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(
                        Decimal("1000000")
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tags",
            field=models.ManyToManyField(related_name="wines", to="wine.Tag"),
        ),
    ]
